name: onTrack-dev

on:
  push:
    branches: ['main']

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.16.0]

    steps:
      - name: Check out repository
        uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Installing dependencies
        run: npm ci
      - name: Running build
        run: npm run build --if-present
      - name: Running Lint
        run: npm run lint
