name: onTrack-dev

on:
  push:
    branches: ['main']

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.16.0]

    steps:
      - name: Check out repository
        uses: actions/checkout@v1
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
          cache: 'npm'
      - name: Installing dependencies
        run: npm ci
      - name: Running build
        run: npm run build --if-present
      - name: Running Lint
        run: npm run lint

  test:
    needs: build
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.16.0]

    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Installing dependencies
        run: npm ci
      - name: 'Running test'
        run: npm test

  deploy:
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: npm install
      - run: npm run build --if-present

      - name: Deploy to netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.DEV_NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=build --prod
          secrets: '["DEV_NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'
